[package]
name = "cotlgif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#spine = { git = "https://github.com/pocams/spine-rs" }
#spine = { path = "../spine-rs/spine" }

rusty_spine = { path = "../rusty_spine" }

triangle = "0.1.353"
fnv = "1.0.7"
itertools = "0.10.5"

sfml = "0.18.1"

imgref = "1.9.4"
gifski = "1.7.2"
rgb = "0.8.34"
