[[actors]]
name = "Lamb"
slug = "player"
atlas = "cotl/player-main.atlas"
skeleton = "cotl/player-main.skel"
order = 100
default_skins = ["Lamb"]
default_animation = "idle"
spoiler_skins = '^(Goat|Owl|Snake|default|effects-top)$'
spoiler_animations = '^(altar-hop|attack-.*OLD|.*blunderbuss.*|attack-combo3-axe-test|.*chalice.*|grabber-.*|grapple.*|intro/goat-.*|lute-.*|oldstuff/.*|shield.*|slide|specials.*|teleport-.*|testing|throw|unconverted.*|warp-out-down-(alt|old)|zipline.*)$'

[[actors]]
name = "Follower"
slug = "follower"
atlas = "cotl/Follower.atlas"
skeleton = "cotl/Follower.skel"
order = 99
default_skins = ["Fox"]
default_animation = "idle"
spoiler_skins = '^(Archer|Badger\d?|Boss Beholder 5|Elephant4|Raccoon\d?|Rhino\d?|.*HorseTown.*|Clothes/(Hooded_Lvl[2345]|NoHouse.*|Robes.*|Warrior)|Hats/Chef|HorseKing|default)$'
spoiler_animations = '^(Buildings/(enter-portal|exit-portal|portal-loop)|Emotions/emotion-insane|Fishing/.*|Food/food-fillbowl|Insane/.*|OldStuff/.*|Possessed/.*|Prison/(stocks-dead.*|stocks-die.*)|TESTING|astrologer|attack-.*|ball|barracks-training|bend-knee|bow-attack.*|bubble.*|convertBUBBLE|cook|devotion/devotion-refused?|hurt-.*|scarify|spawn-in-base-old|studying|sword-.*)$'
has_slot_colours = true

[[actors]]
name = "Forneus"
slug = "forneus"
atlas = "cotl/catSeller.atlas"
skeleton = "cotl/catSeller.skel"
is_spoiler = true
default_skins = ["default"]
default_animation = "animation"
default_scale = 0.3
category = "NPCs"

[[actors]]
name = "Cat seller sheep"
slug = "cat-seller-sheep"
atlas = "cotl/catSellerSheep.atlas"
skeleton = "cotl/catSellerSheep.skel"
is_spoiler = true
default_skins = ["default"]
default_animation = "animation"
default_scale = 0.3
category = "Unused"

[[actors]]
name = "Rakshasa"
slug = "rakshasa"
atlas = "cotl/chefSeller.atlas"
skeleton = "cotl/chefSeller.skel"
default_skins = ["default"]
default_animation = "animation"
category = "NPCs"

[[actors]]
name = "TOWW"
slug = "toww"
atlas = "cotl/DeathBig.atlas"
skeleton = "cotl/DeathBig.skel"
default_skins = ["default", "NoChains"]
default_animation = "idle-crouched"
default_scale = 0.5
category = "Bosses"

[[actors]]
name = "Death cat"
slug = "death-cat"
atlas = "cotl/DeathCat.atlas"
skeleton = "cotl/DeathCat.skel"
is_spoiler = true
default_skins = ["default"]
default_animation = "animation"
category = "Unused"

[[actors]]
name = "Plimbo"
slug = "plimbo"
atlas = "cotl/DecorationShopGuy.atlas"
skeleton = "cotl/DecorationShopGuy.skel"
default_skins = ["default"]
default_animation = "idle"
category = "NPCs"

[[actors]]
name = "Plimbo's fish"
slug = "plimbos-fish"
atlas = "cotl/DecorationShopGuyFish.atlas"
skeleton = "cotl/DecorationShopGuyFish.skel"
default_skins = ["default"]
default_animation = "animation"
default_scale = 0.3
category = "NPCs"

[[actors]]
name = "Fisherman"
slug = "fisherman"
atlas = "cotl/Fisherman.atlas"
skeleton = "cotl/Fisherman.skel"
default_skins = ["default"]
default_animation = "fishing"
category = "NPCs"

[[actors]]
name = "Leshy"
slug = "leshy"
atlas = "cotl/ForestCultLeader.atlas"
skeleton = "cotl/ForestCultLeader.skel"
default_skins = ["default"]
default_animation = "idle"
default_scale = 0.5
category = "Bosses"

[[actors]]
name = "Fox"
slug = "fox"
atlas = "cotl/Fox.atlas"
skeleton = "cotl/Fox.skel"
default_skins = ["default"]
default_animation = "animation"
category = "NPCs"

[[actors]]
name = "Heket"
slug = "heket"
atlas = "cotl/FrogCultLeader.atlas"
skeleton = "cotl/FrogCultLeader.skel"
default_skins = ["default"]
default_animation = "idle"
default_scale = 0.5
category = "Bosses"

[[actors]]
name = "Haro"
slug = "haro"
atlas = "cotl/Haro.atlas"
skeleton = "cotl/Haro.skel"
default_skins = ["default"]
default_animation = "idle"
default_scale = 0.5
category = "NPCs"

[[actors]]
name = "Kallamar"
slug = "kallamar"
atlas = "cotl/JellyBoss.atlas"
skeleton = "cotl/JellyBoss.skel"
default_skins = ["default"]
default_animation = "leader/idle"
default_scale = 0.5
category = "Bosses"

[[actors]]
name = "Flinky"
slug = "flinky"
atlas = "cotl/KnucklebonesPlayer_0_Flinky.atlas"
skeleton = "cotl/KnucklebonesPlayer_0_Flinky.skel"
default_skins = ["Normal"]
default_animation = "animation"
category = "NPCs"

[[actors]]
name = "Klunko and Bop"
slug = "klunko-and-bop"
atlas = "cotl/KnucklebonesPlayer_1_KlunkoAndBop.atlas"
skeleton = "cotl/KnucklebonesPlayer_1_KlunkoAndBop.skel"
default_skins = ["Normal"]
default_animation = "animation"
category = "NPCs"

[[actors]]
name = "Shrumy"
slug = "shrumy"
atlas = "cotl/KnucklebonesPlayer_2_Shrumy.atlas"
skeleton = "cotl/KnucklebonesPlayer_2_Shrumy.skel"
default_skins = ["Normal"]
default_animation = "animation"
category = "NPCs"

[[actors]]
name = "Lighthouse Follower"
slug = "lighthouse-follower"
atlas = "cotl/LighthouseFollower.atlas"
skeleton = "cotl/LighthouseFollower.skel"
default_skins = ["default"]
default_animation = "animation"
category = "NPCs"

[[actors]]
name = "Lighthouse Keeper"
slug = "lighthouse-keeper"
atlas = "cotl/LighthouseKeeper.atlas"
skeleton = "cotl/LighthouseKeeper.skel"
default_skins = ["Axolotl"]
default_animation = "animation"
category = "NPCs"

[[actors]]
name = "Sozo"
slug = "sozo"
atlas = "cotl/mushroomNPC.atlas"
skeleton = "cotl/mushroomNPC.skel"
default_skins = ["default"]
default_animation = "animation2"
category = "NPCs"

[[actors]]
name = "Ratau"
slug = "ratau"
atlas = "cotl/RatNPC.atlas"
skeleton = "cotl/RatNPC.skel"
default_skins = ["normal"]
default_animation = "idle"
category = "NPCs"

[[actors]]
name = "Ratoo"
slug = "ratoo"
atlas = "cotl/Ratoo.atlas"
skeleton = "cotl/Ratoo.skel"
default_skins = ["normal"]
default_animation = "animation"
category = "NPCs"

[[actors]]
name = "Shamura"
slug = "shamura"
atlas = "cotl/Spider.atlas"
skeleton = "cotl/Spider.skel"
default_skins = ["default"]
default_animation = "idle"
default_scale = 0.5
category = "Bosses"

[[actors]]
name = "Helob"
slug = "helob"
atlas = "cotl/SpiderFollowerSeller.atlas"
skeleton = "cotl/SpiderFollowerSeller.skel"
default_skins = ["default"]
default_animation = "animation"
category = "NPCs"

[[actors]]
name = "Clauneck"
slug = "clauneck"
atlas = "cotl/TarotSeller.atlas"
skeleton = "cotl/TarotSeller.skel"
default_skins = ["red"]
default_animation = "idle"
category = "NPCs"

[[actors]]
name = "Midas"
slug = "midas"
atlas = "cotl/MidasNPC.atlas"
skeleton = "cotl/MidasNPC.skel"
default_skins = ["default"]
default_animation = "animation"
category = "NPCs"

[[actors]]
name = "Baal & Aym"
slug = "baal-aym"
atlas = "cotl/DoorGuardians_2.atlas"
skeleton = "cotl/DoorGuardians_2.skel"
default_skins = ["red"]
default_animation = "idle"
# Hide the skins/animations that duplicate Death Cat
spoiler_skins = '^default$'
spoiler_animations = '^(animation|snarling-cat|oldbits.*|.*OLD|.*heart.*|sneakyboirunlol)$'
category = "Minibosses"

[[actors]]
name = "Executioner"
slug = "executioner"
atlas = "cotl/Brute.atlas"
skeleton = "cotl/Brute.skel"
default_skins = ["Executioner"]
default_animation = "idle"
default_scale = 0.5
spoiler_animations = '^(attack-.*|dead.*|die.*|hurt-.*|quickattack.*|run|sleeping|summon|throw|wake-up)$'
category = "Enemies"

[[actors]]
name = "Cultist"
slug = "cultist"
atlas = "cotl/Human.atlas"
skeleton = "cotl/Human.skel"
default_skins = ["Cult_Scamp"]
default_animation = "idle"
category = "Enemies"

[[actors]]
name = "Moth"
slug = "moth"
atlas = "cotl/FireCultMoth.atlas"
skeleton = "cotl/FireCultMoth.skel"
default_skins = ["default"]
default_animation = "idle"
category = "NPCs"

[[actors]]
name = "Witnesses"
slug = "witnesses"
atlas = "cotl/Beholder.atlas"
skeleton = "cotl/Beholder.skel"
default_skins = ["Dungeon1"]
default_animation = "animation"
default_scale = 0.5
category = "Minibosses"

[[actors]]
name = "Burper"
slug = "burper"
atlas = "cotl/burper.atlas"
skeleton = "cotl/burper.skel"
default_skins = ["burper-front"]
default_animation = "idle"
category = "Enemies"

[[actors]]
name = "Charger"
slug = "charger"
atlas = "cotl/Charger.atlas"
skeleton = "cotl/Charger.skel"
default_skins = ["Normal"]
default_animation = "idle"
category = "Enemies"

# Seems broken
#[[actors]]
#name = "Chaser"
#slug = "chaser"
#atlas = "cotl/chaser.atlas"
#skeleton = "cotl/chaser.json"
#default_skins = ["default"]
#default_animation = "idle"

[[actors]]
name = "Chest"
slug = "chest"
atlas = "cotl/Chest.atlas"
skeleton = "cotl/Chest.skel"
default_skins = ["Wooden"]
default_animation = "open"
category = "Objects"

[[actors]]
name = "Crab"
slug = "crab"
atlas = "cotl/Crab.atlas"
skeleton = "cotl/Crab.skel"
default_skins = ["default"]
default_animation = "animation"
category = "Others"

[[actors]]
name = "Crown"
slug = "crown"
atlas = "cotl/crown.atlas"
skeleton = "cotl/crown.skel"
default_skins = ["Lamb"]
default_animation = "idle"
spoiler_skins = "^(Goat|Snake|defaut)$"
spoiler_animations = "^PlayerAnimationBackups.*"
category = "Objects"

[[actors]]
name = "Crown (Big)"
slug = "crown-big"
atlas = "cotl/CrownBig.atlas"
skeleton = "cotl/CrownBig.skel"
default_skins = ["default"]
default_animation = "animation"
category = "Objects"

[[actors]]
name = "TOWW - Boss"
slug = "toww-boss"
atlas = "cotl/DeathCat_Boss.atlas"
skeleton = "cotl/DeathCat_Boss.skel"
default_skins = ["all"]
default_animation = "animation"
default_scale = 0.3
category = "Bosses"

[[actors]]
name = "TOWW - Eyeball"
slug = "toww-eyeball"
atlas = "cotl/DeathCat_Eyeball.atlas"
skeleton = "cotl/DeathCat_Eyeball.skel"
default_skins = ["Normal"]
default_animation = "idle"
category = "Bosses"

[[actors]]
name = "TOWW - Spirit"
slug = "toww-spirit"
atlas = "cotl/DeathCat_Spirit.atlas"
skeleton = "cotl/DeathCat_Spirit.skel"
default_skins = ["default"]
default_animation = "idle"
default_scale = 0.5
category = "Bosses"

[[actors]]
name = "Demon"
slug = "demon"
atlas = "cotl/Demon.atlas"
skeleton = "cotl/Demon.skel"
default_skins = ["Heart"]
default_animation = "idle"
category = "Others"

[[actors]]
name = "Bat"
slug = "bat"
atlas = "cotl/Enemies_Bat.atlas"
skeleton = "cotl/Enemies_Bat.skel"
default_skins = ["Forest"]
default_animation = "Fly"
category = "Enemies"

[[actors]]
name = "Floater"
slug = "floater"
atlas = "cotl/Floater.atlas"
skeleton = "cotl/Floater.skel"
default_skins = ["Spiker"]
default_animation = "animation"
category = "Enemies"

[[actors]]
name = "Eligos"
slug = "eligos"
atlas = "cotl/ForestFlyingFrogMiniboss.atlas"
skeleton = "cotl/ForestFlyingFrogMiniboss.skel"
default_skins = ["default"]
default_animation = "Fly"
category = "Minibosses"

[[actors]]
name = "Leshy (Boss)"
slug = "leshy-boss"
atlas = "cotl/ForestWormBoss.atlas"
skeleton = "cotl/ForestWormBoss.skel"
default_skins = ["default"]
default_animation = "idle"
default_scale = 0.3
category = "Bosses"

[[actors]]
name = "Heket (Boss)"
slug = "heket-boss"
atlas = "cotl/FrogBoss.atlas"
skeleton = "cotl/FrogBoss.skel"
default_skins = ["default"]
default_animation = "idle"
default_scale = 0.3
category = "Bosses"

[[actors]]
name = "Gusion & Zepar"
slug = "gusion-zepar"
atlas = "cotl/FrogMiniBossForest.atlas"
skeleton = "cotl/FrogMiniBossForest.skel"
default_skins = ["MortarMiniboss"]
default_animation = "idle"
category = "Minibosses"

[[actors]]
name = "Goop"
slug = "goop"
atlas = "cotl/Goop.atlas"
skeleton = "cotl/Goop.skel"
default_skins = ["default"]
default_animation = "Goop_0"
category = "Objects"

[[actors]]
name = "Heart guy"
slug = "heart-guy"
atlas = "cotl/heartGuy.atlas"
skeleton = "cotl/heartGuy.skel"
default_skins = ["default"]
default_animation = "animation"
category = "Others"

[[actors]]
name = "Hopper"
slug = "hopper"
atlas = "cotl/Hopper.atlas"
skeleton = "cotl/Hopper.skel"
default_skins = ["hopper-front"]
default_animation = "idle"
category = "Enemies"

[[actors]]
name = "Jelly Bomb"
slug = "jelly-bomb"
atlas = "cotl/JellyBombTrap.atlas"
skeleton = "cotl/JellyBombTrap.skel"
default_skins = ["default"]
default_animation = "animation"
category = "Enemies"

[[actors]]
name = "Anchordeep minibosses"
slug = "jellyfish"
atlas = "cotl/JellyfishMiniboss.atlas"
skeleton = "cotl/JellyfishMiniboss.skel"
default_skins = ["Spiker"]
default_animation = "animation"
default_scale = 0.5
category = "Minibosses"

[[actors]]
name = "Main menu"
slug = "main-menu"
atlas = "cotl/MainMenu.atlas"
skeleton = "cotl/MainMenu.skel"
default_skins = ["default"]
default_animation = "animation"
category = "Others"
default_scale = 0.5

[[actors]]
name = "Millipede & Vephar"
slug = "millipede"
atlas = "cotl/Millipede.atlas"
skeleton = "cotl/Millipede.skel"
default_skins = ["default"]
default_animation = "animation"
default_scale = 0.3
category = "Enemies"

[[actors]]
name = "MiniBossWorm"
slug = "mini-boss-worm"
atlas = "cotl/MiniBossWorm.atlas"
skeleton = "cotl/MiniBossWorm.skel"
default_skins = ["HEAD"]
default_animation = "animation"
category = "Enemies"
is_spoiler = true

[[actors]]
name = "Mortar fly"
slug = "mortar-fly"
atlas = "cotl/MortarFly.atlas"
skeleton = "cotl/MortarFly.skel"
default_skins = ["default"]
default_animation = "animation"
category = "Enemies"

[[actors]]
name = "Patroller & Amdusias & Valefar"
slug = "patroller"
atlas = "cotl/patroller.atlas"
skeleton = "cotl/patroller.skel"
default_skins = ["BABY_BODY_0"]
default_animation = "animation"
category = "Enemies"

[[actors]]
name = "Practise statues"
slug = "practise-statues"
atlas = "cotl/PractiseStatues.atlas"
skeleton = "cotl/PractiseStatues.skel"
default_skins = ["1"]
default_animation = "reform"
default_scale = 0.5
category = "Objects"

[[actors]]
name = "Propaganda speakers"
slug = "propaganda-speakers"
atlas = "cotl/PropagandaSpeakers.atlas"
skeleton = "cotl/PropagandaSpeakers.json"
default_skins = ["default"]
default_animation = "on"
category = "Objects"

[[actors]]
name = "Restaurant worms"
slug = "restaurant-worms"
atlas = "cotl/RestaurantWorms.atlas"
skeleton = "cotl/RestaurantWorms.skel"
default_skins = ["default"]
default_animation = "idle1"
category = "NPCs"

[[actors]]
name = "Scarecrow"
slug = "scarecrow"
atlas = "cotl/Scarecrow.atlas"
skeleton = "cotl/Scarecrow.skel"
default_skins = ["default"]
default_animation = "animation"
category = "Objects"

[[actors]]
name = "Scorpions & Hauras"
slug = "scorpions"
atlas = "cotl/Scorpions.atlas"
skeleton = "cotl/Scorpions.skel"
default_skins = ["Scorpion"]
default_animation = "idle"
category = "Enemies"

[[actors]]
name = "Sermon effect"
slug = "sermon-effect"
atlas = "cotl/SermonEffect.atlas"
skeleton = "cotl/SermonEffect.skel"
default_skins = ["default"]
default_animation = "1-loop"
default_scale = 0.3
category = "Objects"

[[actors]]
name = "Rakshasa's wife"
slug = "snail-seller"
atlas = "cotl/snailSeller.atlas"
skeleton = "cotl/snailSeller.skel"
default_skins = ["default"]
default_animation = "animation"
default_scale = 0.5
category = "NPCs"

[[actors]]
name = "Sorcerer"
slug = "sorcerer"
atlas = "cotl/Sorcerer.atlas"
skeleton = "cotl/Sorcerer.skel"
default_skins = ["Cult"]
default_animation = "idle"
category = "Enemies"
spoiler_skins = ".*OLD.*"

[[actors]]
name = "Spiders & Focalor"
slug = "spiders"
atlas = "cotl/Spiders.atlas"
skeleton = "cotl/Spiders.skel"
default_skins = ["DashSpider_Big"]
default_animation = "idle"
category = "Enemies"

[[actors]]
name = "Squirrel"
slug = "squirrel"
atlas = "cotl/Squirrel.atlas"
skeleton = "cotl/Squirrel.skel"
default_skins = ["default"]
default_animation = "animation"
category = "Others"

[[actors]]
name = "Turret"
slug = "turret"
atlas = "cotl/Turret.atlas"
skeleton = "cotl/Turret.skel"
default_skins = ["Forest Turret"]
default_animation = "idle"
category = "Enemies"

[[actors]]
name = "Weapon card"
slug = "weapon-card"
atlas = "cotl/WeaponCard.atlas"
skeleton = "cotl/WeaponCard.skel"
default_skins = ["None"]
default_animation = "fly"
category = "Objects"
