[package]
name = "cotlgif"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
clap = { version = "4.0.18", features = ["derive"] }
toml = "0.5.9"
